# Dependabot configuration
# docs: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    labels:
      - "dependencies"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/apps/momai"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    labels:
      - "dependencies"
    open-pull-requests-limit: 1
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    open-pull-requests-limit: 1

  - package-ecosystem: "pip"
    directory: "/apps/core"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    open-pull-requests-limit: 1

  - package-ecosystem: "pip"
    directory: "/apps/fortscript"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    open-pull-requests-limit: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "ci/cd"
    open-pull-requests-limit: 5
