import { useEffect, useRef, useState } from 'react'
import sdk from 'momai:sdk'
import {
  createReplySuggestionCache,
  generateReplySuggestions,
  replySuggestionCacheKey,
  type ReplySuggestionContext
} from '../services/replySuggestions'

const cache = createReplySuggestionCache()

// The overlay may expose only the minimal SDK shim (api/events/overlay) instead
// of the full SDK on `window.MomAISDK`. Resolve both surfaces at call time.
function resolveSdkSurfaces(): { llm: any; api: any } {
  const globalSdk =
    typeof window !== 'undefined' ? (window as unknown as { MomAISDK?: any }).MomAISDK : null
  const source = globalSdk || (sdk as any) || {}
  return { llm: source?.llm ?? null, api: source?.api ?? null }
}

export interface UseReplySuggestionsOptions extends ReplySuggestionContext {
  enabled?: boolean
  fallback?: string[]
}

export interface ReplySuggestionsState {
  suggestions: string[]
  /** True while the LLM is generating; the UI should not show fallback yet. */
  loading: boolean
}

/**
 * Contextual WhatsApp reply suggestions generated by the host LLM.
 * While loading it returns no suggestions so the UI can show a placeholder
 * instead of the neutral fallback; the fallback only appears after all
 * attempts fail, keeping repeated opens for the same chat on a short cache.
 */
export function useReplySuggestions(options: UseReplySuggestionsOptions): ReplySuggestionsState {
  const { enabled = true, fallback, ...context } = options
  const [state, setState] = useState<ReplySuggestionsState>(() => ({
    suggestions: [],
    loading: enabled
  }))
  const generationRef = useRef(0)
  const key = replySuggestionCacheKey(context)

  useEffect(() => {
    const generation = generationRef.current + 1
    generationRef.current = generation
    const fallbackList = fallback ?? []

    if (!enabled) {
      setState({ suggestions: fallbackList, loading: false })
      return
    }

    setState({ suggestions: [], loading: true })
    const { llm, api } = resolveSdkSurfaces()
    generateReplySuggestions(llm, context, { cache, fallback: fallbackList, api }).then((next) => {
      if (generation === generationRef.current) setState({ suggestions: next, loading: false })
    })
    // Re-runs only when the contextual key or the enabled flag changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [enabled, key])

  return state
}
